server {
 listen 80;
 server_name _;
 root /usr/share/nginx/html;
 add_header Referrer-Policy "no-referrer" always;
 access_log off;
 add_header X-Robots-Tag "noindex, nofollow" always;
 add_header X-Content-Type-Options "nosniff" always;
 location / { try_files $uri $uri/ /index.html; }
}
